import json
import os
import re
from pathlib import Path

from langgraph.graph import StateGraph, START, END

# Custom Imports
from backend.config import supabase
from backend.state import State

def merge_content(state: State) -> dict:
    plan = state["plan"]
    if plan is None:
        raise ValueError("merge_content called without plan.")
    
    cleaned_sections = []
    for _, md in sorted(state["sections"], key=lambda x: x[0]):
        clean_part = re.sub(r"\{['\"]type['\"]:\s*['\"]text['\"],\s*['\"]text['\"]:\s*['\"](.*?)['\"]\}", r"\1", md, flags=re.DOTALL)
        cleaned_sections.append(clean_part)
    
    body = "\n\n".join(cleaned_sections).strip()
    merged_md = f"# {plan.blog_title}\n\n{body}\n"
    return {"merged_md": merged_md}


DECIDE_IMAGES_SYSTEM = """You are an expert technical editor.
Decide if images/diagrams are needed for THIS blog.

Rules:
- Max 3 images total.
- Each image must materially improve understanding (diagram/flow/table-like visual).
- Insert placeholders exactly: [[IMAGE_1]], [[IMAGE_2]], [[IMAGE_3]].
- If no images needed: md_with_placeholders must equal input and images=[].
- Avoid decorative images; prefer technical diagrams with short labels.
Return strictly GlobalImagePlan.
"""

def decide_images(state: State) -> dict:
    # planner = llm.with_structured_output(GlobalImagePlan)
    # merged_md = state["merged_md"]
    # plan = state["plan"]
    # assert plan is not None

    # image_plan = planner.invoke(
    #     [
    #         SystemMessage(content=DECIDE_IMAGES_SYSTEM),
    #         HumanMessage(
    #             content=(
    #                 f"Blog kind: {plan.blog_kind}\n"
    #                 f"Topic: {state['topic']}\n\n"
    #                 "Insert placeholders + propose image prompts.\n\n"
    #                 f"{merged_md}"
    #             )
    #         ),
    #     ]
    # )

    # return {
    #     "md_with_placeholders": image_plan.md_with_placeholders,
    #     "image_specs": [img.model_dump() for img in image_plan.images],
    # }
    return {
        "md_with_placeholders": state["merged_md"],
        "image_specs": [], 
    }

def _gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini.
    Requires: pip install google-genai
    Env var: GEMINI_API_KEY (or GOOGLE_API_KEY for compatibility)
    """
    from google import genai
    from google.genai import types

    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key: raise RuntimeError("GEMINI_API_KEY is not set.")
    
    client = genai.Client(api_key=api_key)
    
    resp = client.models.generate_content(
        model="gemini-3.1-flash-image",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
            safety_settings=[types.SafetySetting(category="HARM_CATEGORY_DANGEROUS_CONTENT", threshold="BLOCK_ONLY_HIGH")],
        ),
    )
    
    parts = getattr(resp, "parts", None)
    
    if not parts and getattr(resp, "candidates", None):
        try: parts = resp.candidates[0].content.parts
        except Exception: parts = None
    
    if not parts: raise RuntimeError("No image content returned.")
    
    for part in parts:
        inline = getattr(part, "inline_data", None)
        if inline and getattr(inline, "data", None):
            return inline.data
    raise RuntimeError("No inline image bytes found.")

def _safe_slug(title: str) -> str:
    s = title.strip().lower()
    s = re.sub(r"[^a-z0-9 _-]+", "", s)
    s = re.sub(r"\s+", "_", s).strip("_")
    return s or "blog"

def generate_and_place_images(state: State) -> dict:
    plan = state["plan"]
    assert plan is not None

    md = state.get("md_with_placeholders") or state["merged_md"]
    image_specs = state.get("image_specs", []) or []

    images_dir = Path("images")
    images_dir.mkdir(exist_ok=True)

    for spec in image_specs:
        placeholder = spec["placeholder"]
        filename = spec["filename"]
        out_path = images_dir / filename
        if not out_path.exists():
            try:
                img_bytes = _gemini_generate_image_bytes(spec["prompt"])
                out_path.write_bytes(img_bytes)
            except Exception as e:
                md = md.replace(placeholder, f"> **[IMAGE FAILED]** {e}\n")
                continue
        md = md.replace(placeholder, f"![{spec['alt']}](images/{filename})\n*{spec['caption']}*")

    filename = f"{_safe_slug(plan.blog_title)}.md"
    Path(filename).write_text(md, encoding="utf-8")
    
    # Saving Final markdown to state
    state["final"] = md 
    
    # Saving to Supabase (if configured)
    if supabase:
        try:
            def custom_serializer(obj):
                if hasattr(obj, "model_dump"): return obj.model_dump()
                from datetime import date, timedelta
                if isinstance(obj, (date, timedelta)): return str(obj)
                return str(obj)
            
              # state to JSON string 
            state_json = json.loads(json.dumps(state, default=custom_serializer))
            supabase.table("blogs").insert({
                "title": plan.blog_title,
                "content": md,
                "full_state": state_json
            }).execute()
            print(f"✅ Successfully saved '{plan.blog_title}' to Supabase!")
        except Exception as e:
            print(f"❌ Error saving to Supabase: {e}")

    return {"final": md}

# Export the Reducer sub-graph
reducer_graph = StateGraph(State)
reducer_graph.add_node("merge_content", merge_content)
reducer_graph.add_node("decide_images", decide_images)
reducer_graph.add_node("generate_and_place_images", generate_and_place_images)
reducer_graph.add_edge(START, "merge_content")
reducer_graph.add_edge("merge_content", "decide_images")
reducer_graph.add_edge("decide_images", "generate_and_place_images")
reducer_graph.add_edge("generate_and_place_images", END)
reducer_subgraph = reducer_graph.compile()